import type { TraderProfile } from "@/lib/types/trader-profile";

/** Example TraderProfile for development and demo. */
export const MOCK_TRADER_PROFILE: TraderProfile = {
  traderId: "T5-7842-KJ",
  nickname: "AlphaScalper",
  avatar: "AS",
  createdAt: "2024-06-15T00:00:00.000Z",
  countryCode: "IL",
  tier2Verified: true,
  clan: { id: "c1", name: "Elite Scalpers", icon: "⚡" },
  badges: [
    { id: "b1", name: "Funded Trader", icon: "💲" },
    { id: "b2", name: "10K Payout", icon: "💵" },
    { id: "b3", name: "Win Streak", icon: "🔥" },
  ],

  preferredStrategy: "Scalper",
  strategySharePercent: 24,
  qualityScore: 88,
  skills: {
    consistency: 82,
    discipline: 90,
    timing: 85,
    sizing: 78,
    riskManagement: 88,
  },

  topTradedAssets: [
    { symbol: "XAUUSD", label: "XAUUSD", icon: "🥇", assetType: "Metals", tradeCount: 890, sharePercent: 24, winRatePercent: 62, tradeQualityScore: 84 },
    { symbol: "EURUSD", label: "EURUSD", icon: "💱", assetType: "Forex", tradeCount: 1240, sharePercent: 32, winRatePercent: 68, tradeQualityScore: 88 },
    { symbol: "BTCUSD", label: "BTCUSD", icon: "₿", assetType: "Crypto", tradeCount: 456, sharePercent: 12, winRatePercent: 54, tradeQualityScore: 72 },
    { symbol: "GBPUSD", label: "GBPUSD", icon: "💱", assetType: "Forex", tradeCount: 380, sharePercent: 10, winRatePercent: 71, tradeQualityScore: 91 },
    { symbol: "NAS100", label: "NAS100", icon: "📈", assetType: "Indices", tradeCount: 290, sharePercent: 8, winRatePercent: 48, tradeQualityScore: 69 },
  ],

  averages: {
    winRatePercent: 68.4,
    profitFactor: 1.82,
    avgHoldHours: 4.2,
    totalTrades: 3847,
    consistencyScore: 72,
    winRateTopPercent: 60,
    tradeQualityTopPercent: 18,
    communityAvgWinRatePercent: 58.2,
    communityAvgQualityScore: 62,
  },
  activityChart: {
    label: "Monthly Trades",
    period: "Last 6M",
    valueLabels: ["Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
    values: [520, 610, 580, 720, 650, 690],
  },

  achievements: [
    { id: "passEvaluation", name: "Evaluation Passed", description: "Successfully pass your evaluation", icon: "✅", earnedAt: "2024-05-10" },
    { id: "funded", name: "Funded Trader", description: "Get funded for the first time", icon: "💲", earnedAt: "2024-06-01" },
    { id: "firstPayout", name: "First Payout", description: "Receive your first payout", icon: "💸", earnedAt: "2024-08-01" },
    { id: "hugePayout", name: "Huge Withdrawal", description: "Make a withdrawal of $10,000", icon: "💵", earnedAt: "2024-09-15", tier: 2, maxTiers: 5 },
    { id: "contestParticipant", name: "Contest Participant", description: "Participate in a trading contest", icon: "🎯", earnedAt: "2024-07-22" },
    { id: "contest3rd", name: "Contest 3rd Place", description: "Finish 3rd in a trading contest", icon: "🥉", earnedAt: "2024-08-30" },
    { id: "contest2nd", name: "Contest 2nd Place", description: "Finish 2nd in a trading contest", icon: "🥈", earnedAt: "2024-11-20" },
    { id: "totalTrades", name: "Experienced Trader", description: "Make 200 trades", icon: "📊", earnedAt: "2024-10-12", tier: 3, maxTiers: 5 },
    { id: "dailyConsistency", name: "Consistent Trader", description: "Trade 14 days in a row", icon: "🔥", earnedAt: "2024-10-02", tier: 2, maxTiers: 5 },
    { id: "accountDollarProfit", name: "Profit Builder", description: "Build total account profit", icon: "💰", earnedAt: "2024-11-05", tier: 3, maxTiers: 5 },
  ],
  certificates: [
    { id: "c1", name: "Pro Trader Certification", issuer: "The5ers", issuedAt: "2024-07-01" },
  ],

  community: {
    postsCount: 124,
    likesReceived: 892,
    commentsCount: 340,
    sharesCount: 45,
    followersCount: 2456,
    followingCount: 328,
  },

  tradeTalkPosts: [
    {
      id: "p1",
      snippet: "Gold holding key support at 2620 – watching for a bounce into NY session. Risk managed with tight SL.",
      timestamp: "2025-03-17T14:30:00.000Z",
      likesCount: 24,
      commentsCount: 8,
      sparkline: [12, 18, 15, 22, 28, 24, 31, 35, 32, 38],
    },
    {
      id: "p2",
      snippet: "EURUSD scalping the London range. 3 trades, 2 wins. Discipline paid off today.",
      timestamp: "2025-03-16T11:00:00.000Z",
      likesCount: 12,
      commentsCount: 3,
      sparkline: [8, 6, 9, 11, 10, 14, 12, 15],
    },
    {
      id: "p3",
      snippet: "Shared my monthly recap: 68% win rate, 1.82 PF. Consistency over home runs.",
      timestamp: "2025-03-15T09:00:00.000Z",
      likesCount: 56,
      commentsCount: 14,
      sparkline: [42, 45, 48, 52, 55, 58, 62, 65, 68, 70, 72],
    },
    {
      id: "p4",
      snippet: "BTCUSD: trimmed size into the weekend. Funding and volatility both on the radar.",
      timestamp: "2025-03-14T16:20:00.000Z",
      likesCount: 31,
      commentsCount: 6,
      sparkline: [20, 22, 19, 25, 28, 26, 30],
    },
    {
      id: "p5",
      snippet: "GBPUSD: BoE week — standing aside until the dust settles. Patience is the trade.",
      timestamp: "2025-03-13T08:45:00.000Z",
      likesCount: 18,
      commentsCount: 4,
      sparkline: [10, 9, 11, 10, 12, 11, 13],
    },
    {
      id: "p6",
      snippet: "NAS100 opening drive faded — took the reversal only after structure confirmed on 5m.",
      timestamp: "2025-03-12T19:10:00.000Z",
      likesCount: 41,
      commentsCount: 11,
      sparkline: [30, 32, 35, 33, 38, 40, 42],
    },
    {
      id: "p7",
      snippet: "Journal update: fewer trades this week, higher quality. Cutting losers faster.",
      timestamp: "2025-03-11T12:00:00.000Z",
      likesCount: 67,
      commentsCount: 19,
      sparkline: [50, 52, 54, 55, 58, 60, 62],
    },
    {
      id: "p8",
      snippet: "Oil inventory day — stayed flat. Sometimes the best position is no position.",
      timestamp: "2025-03-10T15:30:00.000Z",
      likesCount: 22,
      commentsCount: 5,
      sparkline: [14, 15, 14, 16, 15, 17],
    },
    {
      id: "p9",
      snippet: "Asia session liquidity hunt on yen pairs. One and done; green by lunch.",
      timestamp: "2025-03-09T04:15:00.000Z",
      likesCount: 15,
      commentsCount: 2,
      sparkline: [5, 7, 8, 9, 10, 11],
    },
    {
      id: "p10",
      snippet: "Prop firm rules reminder: daily loss cap saved me twice this month. Respect the guardrails.",
      timestamp: "2025-03-08T10:00:00.000Z",
      likesCount: 89,
      commentsCount: 24,
      sparkline: [60, 62, 65, 68, 72, 75, 78, 82],
    },
  ],

  viewerStats: {
    viewerNickname: "TradeKing",
    qualityScore: 65,
    winRatePercent: 62.1,
    profitFactor: 1.45,
    totalTrades: 1200,
    consistencyScore: 58,
    skills: {
      consistency: 70,
      discipline: 65,
      timing: 72,
      sizing: 60,
      riskManagement: 68,
    },
    viewerTopTradedAssets: [
      { symbol: "XAUUSD", label: "XAUUSD", icon: "🥇", assetType: "Metals", tradeCount: 180, sharePercent: 15, winRatePercent: 58, tradeQualityScore: 70 },
      { symbol: "EURUSD", label: "EURUSD", icon: "💱", assetType: "Forex", tradeCount: 420, sharePercent: 35, winRatePercent: 64, tradeQualityScore: 76 },
      { symbol: "BTCUSD", label: "BTCUSD", icon: "₿", assetType: "Crypto", tradeCount: 96, sharePercent: 8, winRatePercent: 51, tradeQualityScore: 62 },
      { symbol: "GBPUSD", label: "GBPUSD", icon: "💱", assetType: "Forex", tradeCount: 240, sharePercent: 20, winRatePercent: 59, tradeQualityScore: 74 },
      { symbol: "NAS100", label: "NAS100", icon: "📈", assetType: "Indices", tradeCount: 264, sharePercent: 22, winRatePercent: 55, tradeQualityScore: 68 },
    ],
  },
};
